force-app/main/default/objects/Faculty__c/Faculty__c.object-meta.xml
<CustomObject>
    <label>Faculty</label>
    <nameField>
        <label>Faculty Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Faculties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Faculty__c/fields/ManagedBy__c.field-meta.xml
<CustomField>
    <fullName>ManagedBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Managed By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ManagedBy</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FacultyCtrl.cls
public with sharing class FacultyCtrl {
    @AuraEnabled(Cacheable = true)
    public static List<Faculty__c> getFacultyByUser() {
        // if System Admin -> return all
        if (ProfileCtrl.isSystemAdmin()) {
            return [
                SELECT Id, Name, Description__c, ManagedBy__r.Name, Status__c
                FROM Faculty__c
            ];
        }

        // Not admin -> return assigned only
        return getFacultyManagedByUser();
    }

    @AuraEnabled(Cacheable = true)
    public static List<Faculty__c> getFacultyManagedByUser() {
        if (ProfileCtrl.isFacultyAdmin()) {
            String userId = UserInfo.getUserId();
            return [
                SELECT Id, Name, Description__c, ManagedBy__r.Name, Status__c
                FROM Faculty__c
                WHERE ManagedBy__r.Id = :userId 
            ];
        }

        return [
            SELECT Id, Name, Description__c, ManagedBy__r.Name, Status__c
            FROM Faculty__c
        ];
    }

    @AuraEnabled(Cacheable = true)
    public static List<Faculty__c> getFacultyManagedByUserApproved() {
        String userId = UserInfo.getUserId();
       
        
        return [
            SELECT Id, Name, Description__c, ManagedBy__r.Name, Status__c
            FROM Faculty__c
            WHERE ManagedBy__r.Id = :userId 
            AND Status__c = 'Approved'
        ];
    }

    public static List<String> getFacultyIdManagedByUser() {
        String userId = UserInfo.getUserId();
        List<String> idList = new List<String>();

        for (
            Faculty__c f : 
            [
                SELECT Id
                FROM Faculty__c
                WHERE ManagedBy__r.Id = :userId
            ]   
        ) {
            idList.add(f.Id);
        }

        return idList;
    }
}